LEVEL_1 = ['wood', 'thank', 'count', 'add', 'mess', 'mind', 'enemy', 'adult', 'bitter', 'find', 'pray', 'spine', 'dish',
           'immune', 'fly', 'wreck', 'beef', 'fist', 'real', 'fox', 'dull', 'guest', 'report', 'fur', 'rest', 'crude',
           'drab', 'spark', 'shine', 'cake', 'noel', 'carrot', 'grief', 'visual', 'middle', 'symbol', 'stab', 'knife',
           'harsh', 'want', 'flash', 'suffer', 'vessel', 'hall', 'repeat', 'graim', 'theory', 'delay', 'sphere', 'taste', 
           'sour', 'voice', 'rewind', 'carpet', 'hello', 'rain', 'posion', 'blade', 'carve', 'tender', 'frozen', 'modest',
           'mosque', 'mold', 'lamp', 'loot', 'cattle', 'sand', 'relate', 'clue', 'hour', 'steep', 'shiver', 'fate',
           'branch', 'valid', 'major', 'flock', 'ballad', 'hammer', 'form', 'polish', 'stage', 'legend', 'hunger',
           'rotten', 'stalk', 'defy', 'blood', 'angel', 'curse', 'traitor', 'night', 'bridge', 'orion', 'bull', 'bronx', 
           'tangle', 'king', 'match', 'atlas', 'spade', 'thief', 'vow', 'woven', 'brain', 'star', 'teeth', 'gambit',
           'bone', 'cage', 'liar', 'wiped', 'flower', 'dust', 'duke', 'lemon', 'heart', 'allow', 'sharp', 'fire', 'power',
           'magic', 'skin', 'roof', 'crown', 'dream', 'time', 'guide', 'secret','good', 'as', 'dead', 'last', 'slow', 'hybrid',
           'esteem', 'belong', 'one', 'step', 'closer', 'hell', 'above', 'escape', 'great', 'state', 'of', 'love', 'trust', 
           'burn', 'bleed', 'freak', 'punch', 'royal', 'upon', 'stick', 'rush', 'rooster', 'demon', 'sorrow']

LEVEL_2 = ['horseman', 'tonight', 'sleepless', 'feasting', 'without', 'beholder', 'justice', 'blackened', 'flawless', 
           'unforgiven', 'wherever', 'maroon', 'nothing', 'kingdom', 'remember', 'wreck', 'destruct', 'fist', 'perfection', 
           'disposable', 'dull', 'necessity', 'papercut', 'crawling', 'rest', 'crude', 'drab', 'spark', 'shine', 'runaway', 
           'forgotten', 'voltage', 'grief', 'visual', 'middle', 'symbol', 'stab', 'knife', 'harsh', 'foreword', 'flash', 
           'suffer', 'suprises', 'hall', 'repeat', 'lullaby', 'theory', 'bleeding', 'sphere', 'chemistry', 'equality', 
           'sour', 'voice', 'rewind', 'oxigen', 'velvet', 'thorn', 'posion', 'blade', 'carve', 'tender', 'battery', 'watchtower',
           'creeping', 'mold', 'destroy', 'puppets', 'everlasting', 'sandman', 'relate', 'clue', 'evenflow', 
           'parallel', 'shiver', 'universe', 'shimmer', 'serenity', 'destruction', 'flock', 'ballad', 'hammer', 'form', 
           'interstate', 'shelter', 'hunger', 'rotten', 'stalk', 'pretender', 'blood', 'angel', 'curse', 
           'traitor', 'night', 'bridge', 'boulevard', 'bullet', 'bronx', 'tangle', 'butterfly', 'ordinary', 'interlude', 
           'library', 'thief', 'revolution', 'woven', 'brain', 'diamond', 'duality', 'gambit', 'brightside', 'tissue', 
           'everlong', 'wiped', 'flower', 'sanitarium', 'otherside', 'precious', 'heart', 'personal', 'sharp', 'illusion', 
           'power', 'magic', 'aviation', 'identity', 'crown', 'synopsis', 'time', 'guide', 'secret','sculpture', 'mirrorball', 
           'affection', 'comfortably', 'softcore', 'hybrid', 'esteem', 'belong', 'temptation', 'catapult', 'closer', 'treatment', 
           'fireside', 'escape', 'heavenly', 'heartless', 'pressure', 'paranoid', 'backwards', 'forgiveness', 'bleed', 
           'freak', 'glimmer', 'moonlight', 'creature', 'shield', 'affection', 'blossom', 'clockwork', 'villian', 'sorcery',
           'gallant', 'wrath']

LEVEL_3 = ['horseman', 'guillotine', 'feasting', 'apprentice', 'beholder', 'justice', 'blackened', 'flawless', 
           'unforgiven', 'constellation', 'unrequited', 'destruct', 'perfection', 'aneurysm', 'necessity', 'papercut', 
           'crawling', 'paradigm', 'crude', 'charcuterie', 'zucchini', 'accommodate', 'runaway', 
           'forgotten', 'exemption', 'silvertongue', 'nocturnal', 'cigarettes', 'symbol', 'acquiesce',  
           'expertise', 'suprises', 'understatement', 'repeat', 'lullaby', 'chemistry', 'equality', 
           'tranquility', 'perspective', 'rewind', 'oxigen', 'legislation', 'rhapsody', 'posion', 'existentialism', 
           'sovereignty', 'harvester', 'aluminum', 'excess', 'everlasting', 'neighborhood', 
           'parallel', 'misunderstood', 'destruction', 'pizzas', 'dachshund', 
           'interstate', 'excuses', 'accountant', 'rotten', 'obstinance', 'pretender', 'liquefy', 'narcissistic', 'occasion', 
           'traitor', 'characteristic', 'coincidence', 'boulevard', 'negligence', 'bronx', 'interlude', 
           'library', 'credibility', 'revolution', 'hypothesis', 'consensus', 'exemption', 'prejudice',
           'hypnotize', 'stereotype', 'structure', 'precious', 'circumstance', 'negotiation', 'illusion', 
           'power', 'overwhelmed', 'aviation', 'identity', 'frequency', 'synopsis', 'absorption', 'supplementary', 'mirrorball', 
           'affection', 'comfortably', 'extraterrestrial', 'civilization', 'chauvinist', 'heavenly', 'heartless', 
           'pressure', 'paranoid', 'backwards', 'forgiveness', 
           'allocation', 'glimmer', 'modernize', 'clockwork', 'sorcery', 'homicide']